# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.
# shared:
#   api_key: a1B2c3D4e5F6
# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c6b64e47fa8d523a9ea3d7e7658dbd5ee916003785039b14ffdd076fae644afaedc04eb683fc705c47f6f07020184c8cf3a30e79f2258521a45b861ab8e7862
  redis_url_cache: <%= ENV["REDIS_URL_CACHE"] || "redis://localhost:6379/0/cache/" %>
  redis_url: <%= ENV["REDIS_URL_SIDEKIQ"] || "redis://localhost:6379" %>
  prometheus_push_gateway_url: <%= ENV["PROMETHEUS_PUSH_GATEWAY_URL"] %>
  vbms:
    url: https://filenet.uat.vbms.aide.oit.va.gov/vbmsp2-cms/streaming/eDocumentService-v4
    env_dir: ../deployment/decrypted_creds/uat_creds
    keyfile: caseflow_uat_jks
    key: caseflow_uat_keyfile
    saml: caseflow_uat_saml
    keypass: importkey
    cacert: caseflow_uat_ca_cert
    cert: caseflow_uat_client_cert

staging:
  secret_key_base: 8c6b64e47fa8d523a9ea3d7e7658dbd5ee916003785039b14ffdd076fae644afaedc04eb683fc705c47f6f07020184c8cf3a30e79f2258521a45b861ab8e7862
  redis_url_cache: <%= ENV["REDIS_URL_CACHE"] || "redis://localhost:6379/0/cache/" %>
  redis_url: <%= ENV["REDIS_URL_SIDEKIQ"] || "redis://localhost:6379" %>
  prometheus_push_gateway_url: <%= ENV["PROMETHEUS_PUSH_GATEWAY_URL"] %>
  vbms:
    env: uat
    url: https://filenet.uat.vbms.aide.oit.va.gov/vbmsp2-cms/streaming/eDocumentService-v4
    env_dir: ../deployment/decrypted_creds/uat_creds
    keyfile: caseflow_uat_jks
    key: caseflow_uat_keyfile
    saml: caseflow_uat_saml
    keypass: importkey
    cacert: caseflow_uat_ca_cert
    cert: caseflow_uat_client_cert

demo:
  secret_key_base: 8c6b64e47fa8d523a9ea3d7e7658dbd5ee916003785039b14ffdd076fae644afaedc04eb683fc705c47f6f07020184c8cf3a30e79f2258521a45b861ab8e7862
  redis_url_cache: <%= ENV["REDIS_URL_CACHE"] || "redis://localhost:6379/0/cache/" %>
  redis_url: <%= ENV["REDIS_URL_SIDEKIQ"] || "redis://localhost:6379" %>
  prometheus_push_gateway_url: <%= ENV["PROMETHEUS_PUSH_GATEWAY_URL"] %>


test:
  secret_key_base: 35cf2535cc790c92a07bcab48a5f21bbd132a7071984947e8cc92d2ce8e60d582c62022b7ddcfa6f0eca34319dfe1482fbf21d2c78e50c12e884be9ea5fea7e0
  redis_url_cache: <%= ENV["REDIS_URL_CACHE"] || "redis://localhost:6379/0/cache/" %>
  redis_url: <%= ENV["REDIS_URL_SIDEKIQ"] || "redis://localhost:6379" %>
  prometheus_push_gateway_url: <%= ENV["PROMETHEUS_PUSH_GATEWAY_URL"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis_url_cache: <%= ENV["REDIS_URL_CACHE"] %>
  redis_url: <%= ENV["REDIS_URL_SIDEKIQ"] %>
  prometheus_push_gateway_url: <%= ENV["PROMETHEUS_PUSH_GATEWAY_URL"] %>
  vbms:
      env: true
